[package]
name = "password"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "1.0.2"
tokio = { version = "1.25.0", features = ["full"] }
serde_json = "1.0.93"
serde = "1.0.152"